"""Multiple data categories

Revision ID: 66c8e3cf68ba
Revises: be8ccc05f719
Create Date: 2021-01-25 11:42:59.754214

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "66c8e3cf68ba"
down_revision = "be8ccc05f719"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_set_categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("value", sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_data_set_categories_id"), "data_set_categories", ["id"], unique=False
    )
    op.create_table(
        "data_set_result_categories",
        sa.Column("entry_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["data_set_categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["entry_id"],
            ["data_set_result_entries.id"],
        ),
        sa.PrimaryKeyConstraint("entry_id", "category_id"),
    )
    op.drop_column("data_set_result_entries", "category")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "data_set_result_entries",
        sa.Column("category", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_table("data_set_result_categories")
    op.drop_index(op.f("ix_data_set_categories_id"), table_name="data_set_categories")
    op.drop_table("data_set_categories")
    # ### end Alembic commands ###
