"""Drop software ver unique

Revision ID: 6c3c6ba3322f
Revises: f59d68c0a199
Create Date: 2021-02-01 15:25:43.740986

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "6c3c6ba3322f"
down_revision = "f59d68c0a199"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "software_provenance_version_key", "software_provenance", type_="unique"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "software_provenance_version_key", "software_provenance", ["version"]
    )
    # ### end Alembic commands ###
