"""Nullable parameter smirks

Revision ID: e7843137f2e9
Revises: 6c3c6ba3322f
Create Date: 2021-10-18 16:09:42.034719

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e7843137f2e9"
down_revision = "6c3c6ba3322f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("parameters", "smirks", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("parameters", "smirks", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
