"""Update to recharge 0.0.1a4 which adds dft grid setting.

Revision ID: f52bb314d86f
Revises: 570fdd474d67
Create Date: 2020-09-24 15:01:56.097690

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f52bb314d86f"
down_revision = "570fdd474d67"
branch_labels = None
depends_on = None


def upgrade():
    op.add_column(
        "recharge_esp_settings",
        sa.Column(
            "psi4_dft_grid_settings",
            sa.String(),
            nullable=False,
            server_default="default",
        ),
    )
    op.alter_column(
        "recharge_esp_settings", "psi4_dft_grid_settings", server_default=None
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recharge_esp_settings", "psi4_dft_grid_settings")
    # ### end Alembic commands ###
