"""Software provenance

Revision ID: f59d68c0a199
Revises: 66c8e3cf68ba
Create Date: 2021-01-27 11:54:28.746216

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f59d68c0a199"
down_revision = "66c8e3cf68ba"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "software_provenance",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version"),
    )
    op.create_index(
        op.f("ix_software_provenance_id"), "software_provenance", ["id"], unique=False
    )
    op.create_table(
        "benchmark_analysis_environment",
        sa.Column("results_id", sa.Integer(), nullable=False),
        sa.Column("software_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["results_id"],
            ["benchmark_results.id"],
        ),
        sa.ForeignKeyConstraint(
            ["software_id"],
            ["software_provenance.id"],
        ),
        sa.PrimaryKeyConstraint("results_id", "software_id"),
    )
    op.create_table(
        "benchmark_calculation_environment",
        sa.Column("results_id", sa.Integer(), nullable=False),
        sa.Column("software_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["results_id"],
            ["benchmark_results.id"],
        ),
        sa.ForeignKeyConstraint(
            ["software_id"],
            ["software_provenance.id"],
        ),
        sa.PrimaryKeyConstraint("results_id", "software_id"),
    )
    op.create_table(
        "optimization_analysis_environment",
        sa.Column("results_id", sa.Integer(), nullable=False),
        sa.Column("software_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["results_id"],
            ["optimization_results.id"],
        ),
        sa.ForeignKeyConstraint(
            ["software_id"],
            ["software_provenance.id"],
        ),
        sa.PrimaryKeyConstraint("results_id", "software_id"),
    )
    op.create_table(
        "optimization_calculation_environment",
        sa.Column("results_id", sa.Integer(), nullable=False),
        sa.Column("software_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["results_id"],
            ["optimization_results.id"],
        ),
        sa.ForeignKeyConstraint(
            ["software_id"],
            ["software_provenance.id"],
        ),
        sa.PrimaryKeyConstraint("results_id", "software_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("optimization_calculation_environment")
    op.drop_table("optimization_analysis_environment")
    op.drop_table("benchmark_calculation_environment")
    op.drop_table("benchmark_analysis_environment")
    op.drop_index(op.f("ix_software_provenance_id"), table_name="software_provenance")
    op.drop_table("software_provenance")
    # ### end Alembic commands ###
