name: tests

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:

  test:

    runs-on: ${{ matrix.os }}

    strategy:

      matrix:
        python-version: [3.6, 3.7]
        cfg:
          - os: ubuntu-latest
            openeye: "false"

          - os: macOS-latest
            openeye: "false"

          - os: ubuntu-latest
            openeye: "true"

    env:
      OE_LICENSE: ${{ github.workspace }}/oe_license.txt

    steps:
      - uses: actions/checkout@v2

      - name: Setup Conda Environment
        uses: goanpeca/setup-miniconda@v1
        with:
           activate-environment: test
           environment-file: devtools/conda-envs/test_env.yaml
           auto-activate-base: false
           auto-update-conda: true
           python-version: ${{ matrix.python-version }}

      - name: Conda Environment Information
        shell: bash -l {0}
        run: |
          conda info
          conda list

      - name: Install PASCAL Compiler (MacOS)
        shell: bash -l {0}
        if: startsWith(matrix.cfg.os, 'macOS')
        run: |
          brew install fpc

      - name: Install PASCAL Compiler (Ubuntu)
        shell: bash -l {0}
        if: startsWith(matrix.cfg.os, 'ubuntu')
        run: |
          sudo apt-get install fp-compiler

      - name: Install checkmol
        shell: bash -l {0}
        run: |

          curl https://homepage.univie.ac.at/norbert.haider/download/chemistry/checkmol/checkmol.pas > checkmol.pas
          fpc checkmol.pas -S2

          echo "::add-path::."

      - name: Install OpenEye toolkit
        shell: bash -l {0}
        if: matrix.cfg.openeye
        run: |

          echo "${SECRET_OE_LICENSE}" > ${OE_LICENSE}
          conda install -c openeye openeye-toolkits

          python -c "from openeye import oechem; assert oechem.OEChemIsLicensed()"

        env:
          SECRET_OE_LICENSE: ${{ secrets.OE_LICENSE }}

      - name: Install Package
        shell: bash -l {0}
        run: |

          python setup.py develop --no-deps

      - name: Run Tests
        shell: bash -l {0}
        run: |

          pytest -v --cov=nonbonded --cov-report=xml nonbonded/tests/

        env:
          DATABASE_URL: "sqlite:///./nonbonded.db"
          DATABASE_TYPE: "SQLite"
          ACCESS_TOKEN: "1234"
          API_URL: "/api/v1"

      - name: Code Coverage
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          fail_ci_if_error: true
